feat(model): add Allocator class for performant allocations
Xerus2000/eve pull request #42
Opened 2019-11-30 16:05 UTC by anarchuser

It has its own internal heap which it uses to allocate objects next to each other, as opposed to `new` which possibly allocates objects randomly in memory

2019-11-30 16:10 UTC, anarchuser commented
Does not have a concrete implementation yet

2019-12-01 12:36 UTC, anarchuser commented
Files `src/model/allocator/allocator.h` and `test/model/allocator/allocator.cpp` can already be reviewed; they're independent from #39 and from any future implementation of it

2019-12-03 10:30 UTC, xeruf requested changes

2019-12-03 10:30 UTC, Xerus2000 commented on src/config.h
> +#define AMOUNT_ALLOCATED_OBJECTS 10000
```suggestion
#define PREALLOCATED_OBJECTS 10000
```

2019-12-03 10:30 UTC, Xerus2000 commented on src/model/object/entity/individual/individual.h
> +
try to avoid random reformatting ;)

2019-12-03 10:30 UTC, Xerus2000 commented on test/model/allocator/allocator.cpp
> +TEST_CASE ("I can allocate objects always located close to each other") {
```suggestion
TEST_CASE ("Jointly allocated objects are located close to each other") {
```

2019-12-03 14:16 UTC, xeruf approved these changes

2019-12-03 14:40 UTC, merged